Improve yaml parser

diff --git a/dev b/dev
--- a/dev
+++ b/dev
@@ -13,23 +13,38 @@ if [ -e /proc/1/cgroup ] && ! head -n1 /proc/1/sched | grep -qce '\(init\|system
 fi
 
 run() {
+  local cache_dir cache_lc cache_su cache_kl cache_ae cache_ph cache_ne \
+    cache_pi env self_bin self_path pwd traefik_path traefik_dc load_env \
+    dc machine dc_file
+  readonly env=dev
+  readonly self_bin="$(realpath "$0")"
+  readonly self_path="$(dirname "$self_bin")"
+  pwd="$(pwd)"
+  readonly traefik_path="$self_path/traefik"
+  readonly traefik_dc="$traefik_path/docker-compose.yaml"
+  PWD="$pwd"
+  export PWD
+  source "$self_path/help"
   _auto_update() {
+    _load_cache
     touch -d '-16 hours' "$cache_lc"
-    [ "$cache_lc" -nt "$cache_pi" ] && touch "$cache_pi" && $(realpath "$0") pull
+    [ "$cache_lc" -nt "$cache_pi" ] && touch "$cache_pi" && "$self_bin" pull
     [ "$cache_lc" -nt "$cache_su" ] && touch "$cache_su" && self_update && check
     return 0
   }
   _find_dc_and_try() {
     local path="$pwd"
-    while [[ $path != / ]]; do
-      for dc_file in docker-compose.y{a,}ml; do if [ -e "$path/$dc_file" ]; then
+    while [ "$path" != "/" ]; do
+      pwd="$path"
+      if _is_dc; then
         cd "$path"
-        pwd="$path"
         "$@"
         exit $?
-      fi; done
+      fi
       path="$(readlink -f "$path"/..)"
     done
+    echo "Error: No docker compose file found"
+    return 1
   }
   _in_array() {
     local a v="$1"
@@ -37,83 +52,115 @@ run() {
     for a; do [ "$a" == "$v" ] && return 0; done
     return 1
   }
+  _is_dc() {
+    for dc_file in docker-compose.y{a,}ml; do [ -e "$pwd/$dc_file" ] && dc_file="$pwd/$dc_file" && return 0; done
+    return 1
+  }
+  _load_cache() {
+    [ -n "${cache_dir:-}" ] && return 0
+    cache_dir="$HOME/.cache/development-manager-docker-compose"
+    [ ! -e "$cache_dir" ] && mkdir -p "$cache_dir"
+    find "$cache_dir" -type f -mtime +1 -delete
+    declare -A caches
+    caches[cache_lc]="limit_comparison"
+    caches[cache_su]="self_update"
+    caches[cache_kl]="known_locations"
+    caches[cache_ae]="active_environments"
+    caches[cache_ph]="published_hosts"
+    caches[cache_ne]="new_environments"
+    caches[cache_pi]="project_id_$(echo "$pwd" | base64)"
+    for key in "${!caches[@]}"; do
+      [ -z "${!key:-}" ] && eval "$key=\"$cache_dir/${caches[$key]}\""
+      [ ! -e "${!key}" ] && touch "${!key}" && readonly "$key"
+    done
+    return 0
+  }
+  _load_dc() {
+    [ -n "${dc:-}" ] && return 0
+    _load_machine
+    dc="docker-compose --log-level ERROR"
+    [ "$machine" == "windows" ] && dc="winpty docker-compose --log-level ERROR"
+    readonly dc
+    return 0
+  }
+  _load_dependencies() {
+    _load_machine
+    if [ "$machine" == "macos" ]; then
+      which gtouch >/dev/null && touch() { gtouch "$@"; } && return 0
+      echo "Error: Required tools are missing, run: brew install coreutils"
+      exit 1
+    fi
+    return 0
+  }
   _load_env() {
-    [ -n "${pwd:-}" ] && return 0
+    [ -n "${load_env:-}" ] && return 0
+    _load_machine
+    _load_dependencies
+    _load_user
+    _load_ssh_sock
+    _load_dc
+    _load_cache
+    _load_vars
+    _load_network
+    load_env=1
+    return 0
+  }
+  _load_machine() {
+    [ -n "${machine:-}" ] && return 0
     case "$(uname -s | tr '[:upper:]' '[:lower:]')" in
-    linux*) local machine=linux ;;
-    darwin*) local machine=macos ;;
-    mingw*) local machine=windows ;;
+    linux*) machine=linux ;;
+    darwin*) machine=macos ;;
+    mingw*) machine=windows ;;
+    *) echo "Error: Unknown machine type" && exit 1 ;;
     esac
     readonly machine
-    if [[ "$machine" == "macos" ]]; then
-      if which gtouch >/dev/null; then touch() { gtouch "$@"; }; fi
-      echo "Error: Required tools are missing, run: brew install coreutils"
-      return 1
-    fi
-    local env=dev
-    readonly env
+    return 0
+  }
+  _load_network() {
+    [ -n "${HOST_IP:-}" ] && return 0
+    _load_machine
     case "$machine" in
     windows | macos) readonly HOST_IP=host.docker.internal ;;
     linux) readonly HOST_IP=$(ip -4 addr show docker0 | grep -Po 'inet \K[\d.]+') ;;
-    *) echo "Error: Unknown machine type" && exit 1 ;;
     esac
     export HOST_IP
-    if [[ "${SSH_AUTH_SOCK:-}" == "" ]]; then
-      readonly SSH_AUTH_SOCK="/tmp/.ssh-sock"
-      ssh-agent -a "$SSH_AUTH_SOCK" &>/dev/null
-    fi
-    export SSH_AUTH_SOCK
-    readonly UID GID="$(id -g)"
-    export GID UID
-    if [[ "$machine" == "windows" ]]; then
-      readonly DC="winpty docker-compose --log-level ERROR"
-      readonly CUID="1000" CGID="1000" CHOME="/home/app"
-    else
-      readonly DC="docker-compose --log-level ERROR"
-      readonly CUID="$UID" CGID="$GID" CHOME="$HOME"
-    fi
-    export CUID CGID CHOME
-    readonly self_bin="$(realpath "$0")"
-    readonly self_path="$(dirname "$self_bin")"
-    pwd="$(pwd)"
-    readonly traefik_path="$self_path/traefik"
-    readonly traefik_dc="$traefik_path/docker-compose.yaml"
-    readonly cache_dir="$HOME/.cache/development-manager-docker-compose"
-    readonly cache_lc="$cache_dir/limit_comparison"
-    readonly cache_su="$cache_dir/self_update"
-    readonly cache_kl="$cache_dir/known_locations"
-    readonly cache_ae="$cache_dir/active_environments"
-    readonly cache_ph="$cache_dir/published_hosts"
-    readonly cache_ne="$cache_dir/new_environments"
-    PWD="$pwd"
-    export PWD
-    cache_pi="$cache_dir/project_id_$(echo "$pwd" | base64)"
-    source "$self_path/help"
-    [ -e "$cache_dir" ] && mkdir -p "$cache_dir"
-    for i in $( (
-      set -o posix
-      set | grep -E '^cache_' | sed 's/=.*//'
-    )); do
-      [ ! -e "$i" ] && touch "$(eval "echo \$$i")"
-    done
-    find "$cache_dir" -type f -mtime +1 -delete
-    set -a
-    # shellcheck source=/dev/null
-    for i in .env .env.local .env.$env .env.$env.local; do [ -e "$pwd/$i" ] && source "$pwd/$i"; done
-    set +a
     if docker network list --format "{{.Name}}" | grep -xcq gateway; then
       docker network create --driver=bridge --attachable --internal=false gateway &>/dev/null
     fi
     return 0
   }
+  _load_ssh_sock() {
+    if [[ "${SSH_AUTH_SOCK:-}" == "" ]]; then
+      readonly SSH_AUTH_SOCK="/tmp/.ssh-sock"
+      ssh-agent -a "$SSH_AUTH_SOCK" &>/dev/null
+    fi
+    export SSH_AUTH_SOCK
+    return 0
+  }
+  _load_user() {
+    [ -n "${CHOME:-}" ] && return 0
+    _load_machine
+    GID="$(id -g)" CUID="$UID" CGID="$GID" CHOME="$HOME"
+    [ "$machine" == "windows" ] && CUID="1000" CGID="1000" CHOME="/home/app"
+    readonly GID UID CUID CGID CHOME
+    export GID UID CUID CGID CHOME
+    return 0
+  }
+  _load_vars() {
+    set -a
+    # shellcheck source=/dev/null
+    for i in .env .env.local .env.$env .env.$env.local; do [ -e "$pwd/$i" ] && source "$pwd/$i"; done
+    set +a
+    return 0
+  }
   _parse_yaml() {
+    [ -n "${1:-}" ] && [ -n "${2:-}" ] || return 0
     local prefix="$2"
-    local s='[[:space:]]*'
-    local w='[a-zA-Z0-9_\-]*'
-    local fs
-    fs="$(echo @ | tr @ '\034')"
+    local s='[[:space:]]*' w='[a-zA-Z0-9_\-]*' fs
+    fs=$(echo @ | tr @ '\034')
+    # shellcheck disable=SC1087
     sed -ne "s|^\($s\):|\1|" \
-      -e "s|^\($s\)\($w\)$s:${s}[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
+      -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
       -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p" "$1" |
       awk -F"$fs" '{
       indent = length($1)/2;
@@ -125,7 +172,7 @@ run() {
         sub(/-/, "_", $2)
         printf("%s%s%s=\"%s\"\n", "'"$prefix"'",vn, $2, $3);
       }
-    }'
+    }' | tr '`' '"' | sed 's/"\([a-z0-9\-\.][a-z0-9\-\.]*\)"/\\"\1\\"/g'
   }
   _publish_hosts() {
     # shellcheck disable=SC2001
@@ -145,23 +192,25 @@ run() {
   }
   _start_traefik() {
     if ! grep -qxF "$traefik_path" "$cache_ae"; then
-      $DC -f "$traefik_dc" up -d
+      $dc -f "$traefik_dc" up -d
       echo "$traefik_path" >>"$cache_ae"
     fi
     return
   }
   _stop_traefik() {
     if grep -qxF "$traefik_path" "$cache_ae"; then
-      $DC -f "$traefik_dc" down
+      $dc -f "$traefik_dc" down
       grep -xFv "$traefik_path" "$cache_ae" >"$cache_ne" || touch "$cache_ne"
       cp "$cache_ne" "$cache_ae"
     fi
     return
   }
-  attach() { $DC up "$1" && return; }
+  attach() { _load_dc && $dc up "$1" && return; }
   check() {
-    for dc_file in docker-compose.y{a,}ml; do [ -e "$dc_file" ] && break; done
+    _is_dc || return 1
     eval "$(_parse_yaml "$dc_file" "dc_")"
+    echo $dc_file
+    [ -z "${dc_x_custom_type:-}" ] && return 0
     for dc_latest in "$self_path/templates/$dc_x_custom_type"/docker-compose.y{a,}ml; do [ -e "$dc_latest" ] && break; done
     if [ -n "$dc_x_custom_type" ] && [ -e "$dc_latest" ]; then
       eval "$(_parse_yaml "$dc_latest" "dcl_")" &>/dev/null
@@ -174,19 +223,22 @@ run() {
     return 0
   }
   dc() {
-    $DC "$@"
+    $dc "$@"
     return
   }
   # shellcheck disable=SC2120
   down() {
     for arg; do if [ "$arg" == "-a" ]; then
+      echo "$cache_kl"
+      local cache_dir="$HOME/.cache/development-manager-docker-compose"
+      local cache_kl="$cache_dir/known_locations"
       while read -r i; do for dc_file in docker-compose.y{a,}ml; do
         [ -e "$i/$dc_file" ] && cd "$i" && $self_bin down && break
       done; done <"$cache_kl"
       return
     fi; done
     for dc_file in docker-compose.y{a,}ml; do if [ -e "$dc_file" ]; then
-      $DC down "$@"
+      $dc down "$@"
       grep -xFv "$pwd" "$cache_ae" >"$cache_ne" || true
       cp "$cache_ne" "$cache_ae"
       grep -xFvcq "$traefik_path" "$cache_ae" || _stop_traefik
@@ -227,17 +279,15 @@ run() {
     return 1
   }
   ps() {
-    local cache_dir="$HOME/.cache/development-manager-docker-compose"
-    local cache_kl="$cache_dir/known_locations"
+    _load_cache
     for arg; do if [ "$arg" == "-a" ]; then
       while read -r i; do for dc_file in docker-compose.y{a,}ml; do
         [ -e "$i/$dc_file" ] && cd "$i" && echo && echo -e '\E[32m'"\033[1m$i \033[0m" && $(realpath "$0") ps && break
       done; done <"$cache_kl"
       return
     fi; done
-set -e
-    for dc_file in docker-compose.y{a,}ml; do [ -e "$dc_file" ] && $(realpath "$0") dc ps "$@" && break; done
-    return
+    for dc_file in docker-compose.y{a,}ml; do [ -e "$dc_file" ] && $(realpath "$0") dc ps "$@" && return 0; done
+    return 1
   }
   restart() {
     $self_bin down "$@"
@@ -254,20 +304,24 @@ set -e
   up() {
     _auto_update
     for dc_file in docker-compose.y{a,}ml; do [ -e "$dc_file" ] && break; done
+    [ ! -e "$dc_file" ] && return 1
     grep -Eq "[^#]*traefik" "$dc_file" && _start_traefik
-    grep -qxF "$pwd" "$cache_kl" &>/dev/null || pwd >>"$cache_kl"
-    $DC up -d "$@"
-    grep -qxF "$pwd" "$cache_ae" &>/dev/null || pwd >>"$cache_ae"
+    grep -qxF "$pwd" "$cache_kl" &>/dev/null || echo "$pwd" >>"$cache_kl"
+    $dc up -d "$@"
+    grep -qxF "$pwd" "$cache_ae" &>/dev/null || echo "$pwd" >>"$cache_ae"
     ! grep -q "dev_domain=" "$dc_file" || _publish_hosts
     return
   }
   local dc_proxy=(build exec logs pull run)
   readonly dc_proxy
-  if _in_array "${1:-}" "${dc_proxy[@]}"; then _load_env && _find_dc_and_try $DC "$@" && return || exit $?; fi
+  # shellcheck disable=SC2086
+  if _in_array "${1:-}" "${dc_proxy[@]}"; then _load_env && _find_dc_and_try $dc "$@" && return || exit $?; fi
   local global_actions=(help init self_update ps)
   readonly global_actions
-  if _in_array "${1:-}" "${global_actions[@]}"; then "$@" && return || exit $?; fi
-  if [ "$(type -t "${1:-}")" == "function" ]; then _load_env && _find_dc_and_try "$@" && return || exit $?
+  if _in_array "${1:-}" "${global_actions[@]}"; then "$@" && return || _find_dc_and_try "$@" && return || exit $?; fi
+  if [ "$(type -t "${1:-}")" == "function" ]; then
+    # shellcheck disable=SC2086
+    _load_env && "$@" && return || _find_dc_and_try "$@" && return || exit $?
   else source "$(dirname "$(realpath "$0")")/help" && help "$@" && return 1 || exit $?; fi
 }
 run "$@" && exit $?
